from pathlib import Path
import json,hashlib,shutil
from mem_local import call
P=Path(r'D:\Biblioteca\Bioquímica 1º ano 2025-2026\2º Semestre\Vasco M. Barreto\Safe Harbor Canino');O=P/'06_v1.21.6'
note='''# Checkpoint v1.21.6 — variantes, conservação e evidência T

2026-09-14. Limpeza técnica; relatório de apresentação continua adiado. Não é uma nova corrida global ATAC nem validação funcional de safe harbor.

SNPs/nonSNPs: consulta indexada das três janelas de 1 kb remapeadas integralmente para UU_Cfam_GSD_1.0, com os mapeamentos da v1.21.5. Release Dog10K de 1 987 amostras, diferente do subconjunto publicado de 1 929 e das 1 879 amostras do catálogo SV. Não representa os 76 cães do projeto. Duas implementações independentes (HTSlib remoto e HTTP Range + leitura TBI/BGZF) concordaram nas contagens por janela/callset. Os 78 registos recuperados têm REF confirmado contra o FASTA UU local. VCFs locais preservam genótipos, cabeçalhos e filtros; nenhuma chamada filtrada foi silenciosamente promovida a PASS.

Contagens PASS por janela: ANO2 20 SNPs + 1 nonSNP; LOC119876429 13 + 2; NPNT 23 + 8. Com AF de alelo alternativo ≥1%: ANO2 8 SNPs + 1 nonSNP; LOC 3 + 0; NPNT 9 + 3. AF é do catálogo agregado, não probabilidade de um animal ter determinada variante. NonSNP é a classe original do fornecedor, não presumimos que todos os eventos tenham uma única classe de indel. Os números são descritivos, sem novo veto de frequência. As outras 2 088 janelas não foram avaliadas para variantes; continuam explicitamente desconhecidas.

Fonte: https://kiddlabshare.med.umich.edu/dog10K/SNP_and_indel_calls_2021-10-17/ e callset.README.txt. Artefactos: *.local.vcf, *.local.tsv, *.lookup.json, *.provenance.json, small_variant_frequencies.tsv, variant_validation.json. A consulta foi regional; não descarregámos os VCFs completos de centenas de GB.

Revisão SV NPNT: os três genótipos FT PASS da deleção agregada ~28,9 Mb pertencem a GBGV000001 (Grand Basset Griffon Vendeen), PBGV000010 e PBGV000012 (Petit Basset Griffon Vendeen). BFDB000001 (Basset Fauve de Bretagne) tem FAIL3. Todos têm 23 SNPs PASS locais chamados e zero heterozigóticos nessa janela; isto não contradiz a hipótese de hemizigotia, mas uma região de homozigotia pode produzir o mesmo padrão. Não confirma a deleção, nem prova que exista nos animais do projeto. O alerta mantém-se sem veto automático. Metadados e genótipos auditáveis em NPNT_SV_carriers_review.json. Fonte e critérios do fornecedor: https://kiddlabshare.med.umich.edu/dog10K/Manta-SV_2022-03-28/svcallset.v2.README.txt ; amostras: https://kiddlabshare.med.umich.edu/dog10K/sample-information/ .

Conservação: ajuste de apenas um parâmetro (escala da árvore) numa segunda região aleatória chr1:97942942, distinta da região usada no modelo piloto. Matriz de substituição, frequências e proporções de ramos mantidas. Escala relativa estimada ≈0,85019. Não é um modelo neutro independente validado: a região não foi filtrada por repetições ancestrais e herda parâmetros do piloto. Recalculámos as mesmas 3 000 bases locais com ambos os modelos. Máximo da média móvel 50 bp, piloto → escala alternativa: ANO2 1,99976 → 1,44890; LOC 0,97258 → 0,54372; NPNT 1,56628 → 1,05400. Portanto os valores absolutos dependem da calibração e não devem ser tratados como definitivos. Comandos, modelos, MAFs locais e WIGs preservados.

A reprodução das WIGs históricas com o piloto foi exata em ANO2; em LOC/NPNT houve diferenças máximas por base de 0,034/0,033. A execução local reporta poda de espécies sem alinhamento; a causa completa destas pequenas diferenças não foi estabelecida. A comparação de sensibilidade usa os mesmos MAFs locais para os dois modelos. Não sobrescrevemos WIGs históricas nem declaramos a conservação fechada. Ver local_phylop_reproduction.json e conservation_sensitivity_summary.json.

Evidência T pública: identificado GSE244116 / GSM7807442, multiome de um osteossarcoma primário de um Doberman, montagem canFam6 GCF_000002285.5. Matriz H5 de 66 488 728 bytes descarregada e verificada por tamanho/SHA-256; contém 5 969 núcleos, 35 555 features de expressão e 102 989 picos. Inspeção direta deteta 104 núcleos com pelo menos dois dos marcadores core T disponíveis (CD3D/E/G; TRAC não consta como símbolo correspondente). Isso é inventário de marcadores, não anotação validada das células. O GEO disponibiliza também fragmentos ATAC (~1,8 GB), ainda não descarregados. Falta reconstruir identidade celular, resolver montagem e medir loci nos fragmentos. Ausência numa matriz de picos não demonstra cromatina fechada. É um único contexto tumoral, não evidência de células T saudáveis, ativadas ou CAR-T. Fontes: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE244116 e https://github.com/rln0005/OSA_snMultiomeSeq .

Decisão explícita: local_windows_evidence_status.tsv acrescenta os estados de evidência às 2 091 janelas. Mantém scores anteriores; não cria nova classificação numérica. Nas três janelas selecionadas anteriormente, ANO2/NPNT têm conflito regulatório EpiC a resolver; LOC tem evidência insuficiente para safe harbor, apesar de não sobrepor promotor/enhancer nos 11 tecidos analisados. Nenhuma janela recebe aprovação funcional. Missing variants permanecem unknown; PASS VCF não é PASS safe harbor.

Prioridades restantes: (1) medir acessibilidade específica de T cells após anotação celular e harmonização de montagem; (2) resolver evidência regulatória local sem eliminar arbitrariamente todos os picos ATAC; (3) confirmar a chamada SV NPNT com dados de leitura/ortogonais; (4) calibrar conservação com dados neutros adequados e resolver pequenas diferenças de reprodução; (5) concluir recuperação/reconstrução global ATAC/QC; (6) avaliar a sequência individual e demonstrar expressão estável e neutralidade funcional no contexto CAR-T. LOC é relativamente menos problemático nas anotações locais consultadas, não um vencedor validado. Não há protocolo computacional que substitua essa validação biológica.
'''
for f in Path('.').glob('*v1216.py'):shutil.copy2(f,O/f.name)
(O/'CURRENT.md').write_text(note,encoding='utf-8')
shutil.copy2(P/'CURRENT.md',O/'previous_CURRENT.md')
(P/'CURRENT.md').write_text('# Estado atual: v1.21.6\n\n[Checkpoint técnico](06_v1.21.6/CURRENT.md). Variantes locais verificadas; estado de evidência explícito para 2 091 janelas. Nenhum safe harbor validado. Scoring global anterior preservado; relatório adiado.\n',encoding='utf-8')
notes=Path(r'D:\Biblioteca\Biblioteca\Labs\Vasco Barreto Lab\Notas');name='Safe Harbor CAR-T - Checkpoint tecnico v1.21.6 - 2026-09-14';dest=notes/(name+'.md');dest.write_text(note,encoding='utf-8')
moc=notes/'MOC-SafeHarbor Canino CAR-T.md';m=moc.read_text(encoding='utf-8');anchor='# 00 · MOC — Safe Harbor Canino para CAR-T';assert anchor in m
shutil.copy2(moc,O/'previous_obsidian_MOC.md');m=m.replace(anchor,anchor+f'\n\n> [!important] Checkpoint v1.21.6\n> [[{name}]]: variantes locais e revisão SV, sensibilidade da conservação e matriz multiome pública verificadas. Nenhum safe harbor validado.\n',1);moc.write_text(m,encoding='utf-8')
r=call('mempalace_add_drawer',{'wing':'Locus Canino','room':'v1.21.6_Technical_Cleanup','content':note,'source_file':str(dest),'added_by':'Codex'})
(O/'mempalace_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf-8');assert not r.get('error') and not r.get('result',{}).get('isError')
(O/'file_hashes.json').write_text(json.dumps({p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in O.iterdir() if p.is_file() and p.name!='file_hashes.json'},indent=2))
print('v1.21.6 saved to project, Obsidian and MemPalace.')
